### ISSUE TITLE
Release Date for 2.0?

### ISSUE THREAD

**Issue by Ethanbthan14** [jackhumbert/let_there_be_flight#72] opened 2023-12-04 09:39 UTC
Hi, I'm not trying to rush anything; but this is one of my favourite mods. I just want to ask if there is an approximation for when this mod will be updated to 2.0
Thank you

**Comment by londonbrown** [comment] 2023-12-10 08:03
Duplicate of #70 

Ask yourself, is this really helpful or worthy of creating a new issue? 

Friendly reminder that while this is easily one of the best mods available for Cyberpunk 2077, it is a **FREE** mod under the very permissive [MIT License](https://opensource.org/license/mit/), meaning anyone can fork this and update it if they have the necessary skills and time. Otherwise, we should respect the author's time and desired level of commitment as there is no requirement on the author to provide you with updates or to even update the mod in the first place. Jack provided an update in the original issue back in Septemebr: https://github.com/jackhumbert/let_there_be_flight/issues/70#issuecomment-1741863904

Consider checking [existing issues](https://github.com/jackhumbert/let_there_be_flight/issues) before creating a new on in the future, choom.

**Comment by PixelSymbols** [comment] 2023-12-24 18:59
@londonbrown 

its not a "Friendly reminder", you're being rude.
> Ask yourself, is this really helpful or worthy of creating a new issue?
> before creating a new on in the future, choom.

you're being passive-aggressive. Pretty toxic.

**Closed** 2024-02-06 21:48 UTC
